/******************************************************************************
**
** FILE NAME
**    sp_caculator_errorcode.h
**
** DESCRIPTION
**    
**
** History:
**  $Author:    caoqy
**  $Revision:  $
**  $Date:      2017.3.9
**  $Header:    $
*******************************************************************************/
#ifndef _SP_CACULATOR_ERRORCODE_H_
#define _SP_CACULATOR_ERRORCODE_H_

typedef  int  ErrorCode;

#define NGB_SUCCESS  0
// 解析时的错误
#define NGB_EXPRESS_ERROR_BASE      0
#define NGB_EXPRESS_INVALID_EXP     (NGB_EXPRESS_ERROR_BASE + 1)
#define NGB_EXPRESS_QUOTE_NMATCH    (NGB_EXPRESS_ERROR_BASE + 2)
#define NGB_EXPRESS_BRACE_ERROR     (NGB_EXPRESS_ERROR_BASE + 3)
#define NGB_EXPRESS_INVALID_ASN     (NGB_EXPRESS_ERROR_BASE + 4)
// 运行错误
#define NGB_EXPRESS_INVALID_VALUE           (NGB_EXPRESS_ERROR_BASE + 100)
#define NGB_EXPRESS_TYPE_NOTMATCH           (NGB_EXPRESS_ERROR_BASE + 101)
#define NGB_EXPRESS_TYPE_CHANGE_FAILED      (NGB_EXPRESS_ERROR_BASE + 102)
#define NGB_EXPRESS_DEVIDEBY_ZERO           (NGB_EXPRESS_ERROR_BASE + 103)
#define NGB_EXPRESS_UNKNOW_OPER             (NGB_EXPRESS_ERROR_BASE + 104)
#define NGB_EXPRESS_DATAGET_NOTSUPPORTED    (NGB_EXPRESS_ERROR_BASE + 105)
#define NGB_EXPRESS_DATASET_NOTSUPPORTED    (NGB_EXPRESS_ERROR_BASE + 106)
#define NGB_EXPRESS_RUNTIME_OP_INVALID_ADD  (NGB_EXPRESS_ERROR_BASE + 107)
#define NGB_EXPRESS_RUNTIME_OP_INVALID_SUB  (NGB_EXPRESS_ERROR_BASE + 108)
#define NGB_EXPRESS_RUNTIME_OP_INVALID_MUL  (NGB_EXPRESS_ERROR_BASE + 109)
#define NGB_EXPRESS_RUNTIME_OP_INVALID_DIV  (NGB_EXPRESS_ERROR_BASE + 110)
#define NGB_EXPRESS_RUNTIME_OP_INVALID_BOR  (NGB_EXPRESS_ERROR_BASE + 111)
#define NGB_EXPRESS_RUNTIME_OP_INVALID_BND  (NGB_EXPRESS_ERROR_BASE + 112)
#define NGB_EXPRESS_RUNTIME_OP_INVALID_HAS  (NGB_EXPRESS_ERROR_BASE + 113)
#define NGB_EXPRESS_RUNTIME_OP_INVALID_EQL  (NGB_EXPRESS_ERROR_BASE + 114)
#define NGB_EXPRESS_RUNTIME_OP_INVALID_GT   (NGB_EXPRESS_ERROR_BASE + 115)
#define NGB_EXPRESS_RUNTIME_OP_INVALID_LT   (NGB_EXPRESS_ERROR_BASE + 116)
#define NGB_EXPRESS_RUNTIME_OP_INVALID_GTE  (NGB_EXPRESS_ERROR_BASE + 117)
#define NGB_EXPRESS_RUNTIME_OP_INVALID_LTE  (NGB_EXPRESS_ERROR_BASE + 118)
#define NGB_EXPRESS_RUNTIME_OP_INVALID_OR   (NGB_EXPRESS_ERROR_BASE + 119)
#define NGB_EXPRESS_RUNTIME_OP_INVALID_AND  (NGB_EXPRESS_ERROR_BASE + 120)

#define NGB_EXPRESS_USERDEFINED             (NGB_EXPRESS_ERROR_BASE + 1000)



#endif

